Update SECURITY.md
oracle/weblogic-remote-console pull request #49
Opened 2023-06-13 11:44 UTC by spavlusieva

2023-06-13 17:19 UTC, mriccell requested changes

2023-06-13 17:19 UTC, mriccell commented on CONTRIBUTING.md
> +vulnerability, do not raise a GitHub issue and follow the instructions in our
The Remote Console is supported why can we not provide guidance to the user who encounters a security vulnerability to open an SR with Oracle Support?

2023-06-13 17:19 UTC, mriccell commented on SECURITY.md
> +Security updates will be released on a regular cadence. Many of our projects
There are two different ways to address security fixes in the WebLogic Remote Console:
1. Any Security fixes required by the WebLogic Remote Console application will be released soon after the Security vulnerability has been reported/found.
2. Fixes for the WebLogic Remote Console components that run on WebLogic Server will be addressed on a quarterly basis in conjunction with other CPU fixes.

2023-06-13 21:26 UTC, lfeigen commented on SECURITY.md
> +Security updates will be released on a regular cadence. Many of our projects
Yes, I agree.  We do not restrict ourselves to the quarterly cadence.

2023-10-25 13:28 UTC, spavlusieva commented
@mriccell the SECURITY.md file has been updated. Could you please review it? Thank you

2024-05-06 08:08 UTC, closed without merging

2024-05-06 08:08 UTC, LesiaChaban commented
Closed due to a large number of conflicts